services:
  web1:
    image: nginx:alpine
    container_name: web1
    volumes:
      - ./web1/index.html:/usr/share/nginx/html/index.html:ro

  web2:
    image: nginx:alpine
    container_name: web2
    volumes:
      - ./web2/index.html:/usr/share/nginx/html/index.html:ro

  balancer:
    image: nginx:alpine
    container_name: balancer
    ports:
      - "8081:80"
    volumes:
      - ./balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
